# Generated by Django 5.0.4 on 2024-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images')),
                ('image_big_size', models.ImageField(upload_to='images')),
                ('git_hub_link', models.CharField(max_length=300)),
            ],
        ),
    ]
